BeatAroundTheBuscher/ROSIGMA

Ruleset/SM/training_mission_SM.rul
Ruleset/ufopedia40k.rul

the malthus lascannon and the harmonic melta gun were missing their codex pages for space marines. also the harmonic melta had a chaos requisite for unlock (chaos variant has its own codex page). the light lascannon page had a regular lascannon research as a requisite. the chaos harmonic melta gun page was restricted to adeptas, and it was located in the wrong section (I think).

some codex fixes. one turn SM training mission.

---

Language/en-US.yml
Ruleset/SM/research_SM.rul
Ruleset/SM/ufopaedia_SM.rul

just a small qol change.
now you can actually see what will you get for researching the "Light Craft" (now named the "Landspeeder Requisition") topic.

Landspeeder in the TTV, Drop Pod Codex page

---

Ruleset/scripts/scripts_tenacious_enemies.rul

disables the tenacious scripts for melta damage, meaning melta damage wont be converted to stun damage when hitting necrons, unlike other weapons

tenacious script update

---

Language/en-US.yml
Language/ru.yml
Ruleset/ALLFACTIONS/personal_light.rul
Ruleset/SM/GREY KNIGHTS/armors_GK.rul
Ruleset/SM/GREY KNIGHTS/armors_layers_GK.rul
Ruleset/SM/GREY KNIGHTS/armors_scripts_GK.rul
Ruleset/SM/GREY KNIGHTS/ufopaedia_GK.rul
Ruleset/SM/items_SM.rul
Ruleset/SM/scripts_SM.rul

Adds 2 tile Snap Shot thrust attack to Force Halberd that can be used for longer range pseudomelee.
Adds Captain level scaling to Techmarine and Apothecary Aegis armors. Apothecary Aegis has access to better Nartheciums at Paladin and Captain rank.
Rebalance of GK Armors.
GK Librarian now has the custom Holocaust short range fire based psychic power instead of Shield and Lockdown, and Psi Vision 3 and 4 respectively at Paladin and Captain rank. Deals incendiary damage, and deals damage to morale and armor, igniting and hitting a fixed Radius 2 AoE.
Player controlled Eldar Seers now can use their Eldar Light psychic power (aimed shot only)
Space Marines and Grey Knights now recover from wounds in 1/3rd the normal time like Ogryns due to their superior physiology.
Primaris Marines now …

Mostly Grey Knight Update

---

Language/en-US.yml
Ruleset/SM/GREY KNIGHTS/armors_GK.rul
Ruleset/SM/items_SM.rul
Ruleset/SM/scripts_SM.rul
Ruleset/ufopedia40k.rul

-Added a player version of Eldar Lightning for player Farseers that scales somewhat with psi; UFOpaedia entry is unlocked upon researching psychic powers and a live Eldar Farseer.
-Fixed GK Apothecary armor for Castellans not displaying their UFOpaedia entry appropriately.
-Slightly nerfed the Holocaust spell; made its accuracy scale slightly with psi.
-Tweaked GK Librarian armor to be more competitive at Captain/Rank 5; gets Shield 80, Psi Vision 5 up from 4, and Melee Accuracy 15.
-Fixed bug with Chaplain not getting its Crozius.
-Improved/updated UFOpaedia entries.

Minor GK Changes

---

Language/en-US.yml
Language/ru.yml
Ruleset/ALLFACTIONS/personal_light.rul
Ruleset/SM/GREY KNIGHTS/armors_GK.rul
Ruleset/SM/GREY KNIGHTS/soldiers_GK.rul
Ruleset/SM/GREY KNIGHTS/ufopaedia_GK.rul
Ruleset/SM/items_SM.rul
Ruleset/SM/scripts_SM.rul
Ruleset/Voices_40k.rul

-Whitespace removal.
-Added Inquisition Flamer Stormtrooper subtype; grants access to a mastercrafted flamer with some bonus range and accuracy and double tap Snap Shots. Deals TU and extra Morale damage.
-Fixed Inquisition Stormtroopers having a max psy strength of 0.
-Inquisition Stormtroopers now start with a fairly high Devotion because they are elite servants of the Inquisition who are rigorously screened and tested for loyalty.
-Inquisition Stormtroopers PsiDefense enhanced: they now gain a bonus to it equal to 100 + their Devotion and their current Morale, reflecting the impact of their training, discipline and Hexagrammic wards.
-Fixed minor UFOpaedia redundancy/bugs.

Inquisition Stormtrooper Tweaks

---

Ruleset/ENEMY/NURGLE/armors_nurgle.rul
Ruleset/ENEMY/NURGLE/units_nurgle.rul
Ruleset/ENEMY/armors_daemon.rul
Ruleset/ENEMY/weapons_chaos.rul
Ruleset/ENEMY/weapons_daemons.rul
Ruleset/scripts/scripts_bomberman.rul
Ruleset/scripts/scripts_infection_mechanics.rul

Per title.
1. You can now choose to give Bomberman script grenades a set or random duration.
2. Plaguebearers can now spawn with a Boomer bomb with certain loadouts; they've also been given stat tweaks so they can actually throw their Nurgling grenades and more of Nurgle's sacred number.

Minor Refactor/Functionality Improvement for Bomberman Scripts

---

Ruleset/ENEMY/SLAANESH/weapons_slaanesh.rul
Ruleset/ENEMY/armors_daemon.rul
Ruleset/scripts/scripts_reinforcements_less_tus.rul

-Added ARMOR_REINFORCEMENT_TU_PERCENT tag, allowing for the specification of the percentage of max TU reinforcements/spawned units are created with. Defaults to 25% of max TU if unspecified.
-Daemonettes now spawn with 10% of their max TUs instead of 25%.
-Added corruption/infection parameters to Slaanesh Missiles; reduced some of its debuff values to offset the infection damage.

Expanded Reinforcement TU Reduction Scripts

---

Language/en-US.yml
Ruleset/40k.rul
Ruleset/ENEMY/GENE/weapons_gene.rul
Ruleset/ENEMY/SLAANESH/weapons_slaanesh.rul
Ruleset/ENEMY/TZEENTCH/armors_tzeentch.rul
Ruleset/ENEMY/TZEENTCH/weapons_tzeentch.rul
Ruleset/ENEMY/armors_chaos.rul
Ruleset/ENEMY/armors_daemon.rul
Ruleset/ENEMY/weapons_chaos.rul
Ruleset/ENEMY/weapons_daemons.rul
Ruleset/itemCategories.rul
Ruleset/research40k.rul
Ruleset/scripts/scripts_infection_items.rul
Ruleset/scripts/scripts_infection_mechanics.rul
Ruleset/vars40k.rul

1. Expanded and improved the infection scripts to include Tzeentch corruption. Most Tzeentch spells and daemonic melee inflicts some level of Tzeentch corruption.
2. Inferno Bolter ammo stats changed to behave closer to canon (i.e. potentially igniting targets with fire, melting armor; higher ToArmorPre).
3. Changed Tzeentch Flamer daemons to have a short range pink fire flamethrower attack and a medium ranged multi-melta style attack.
4. Changed Glimmering Daemons to resist energy/heat based attacks but resist physical ones. Gave them a rapid fire warp fire attack for close range and a scattershot warpfire attack for medium range.
5. Pink Horrors now spawn two Blue Horrors as they should with a spawner grenade that only activates on death.
6. Rubric Marines and Tzeentch Daemons made …

Tzeentch Overall + Tzeentch Corruption/Infection Functionality

---

Language/en-US.yml
Language/ru.yml
Ruleset/ENEMY/GENE/armors_gene.rul
Ruleset/ENEMY/GENE/units_gene.rul
Ruleset/ENEMY/NURGLE/armors_nurgle.rul
Ruleset/ENEMY/TRAITOR_GUARD/armors_traitor_guard.rul
Ruleset/ENEMY/weapons_chaos.rul
Ruleset/ENEMY/weapons_daemons.rul
Ruleset/scripts/scripts_bomberman.rul

1. Bomberman Scripts now activate the fuse on grenades tagged with ITEM_IS_BOMB when the triggering unit attacks if that unit's armor also has the ARMOR_IS_KAMIKAZI  tag.
2. Bomberman Scripts will now auto kill a unit with armor that has the ARMOR_IS_KAMIKAZI tag when their ITEM_IS_BOMB flagged grenade hits a unit.
3. Removed bomberman script dummy trigger items as they're no longer necessary.
4. Corrected Nurgling spit lacking PreArmorDamage it should have (fix of opportunity).

Bomberman Script Improvements

---

Ruleset/ENEMY/items_spawner.rul
Ruleset/ENEMY/weapons_chaos.rul
Ruleset/ENEMY/weapons_daemons.rul

1. Bomberman Script kamikazi/death bombs can no longer be thrown.
2. Added missing infection damage parameters to Nurgling and Plaguebearer spawner grenades.
3. Whitespace removal.

Fixes Bomberman Script Kamikazi/Death Bombs Being Thrown?

---

Language/en-US.yml
Ruleset/SM/GREY KNIGHTS/manufacture_GK.rul
Ruleset/SM/GREY KNIGHTS/soldiers_GK.rul

1. Grey Knights can now be recruited for $1,000,000 and 200 Honor Tokens for players that have opted for the Grey Knight Chamber Militant sub-path.
2. Grey Knights min psi strength is now 60 and max is 110 as they are all capable psykers at a minimum.
3. Grey Knight min Bravery is now 80 up from 60.

Grey Knights Recruitable for $$$ and Honor Tokens; Stat Tweaks

---

Language/en-US.yml
Ruleset/ADEPTAS/weapons_adeptas.rul
Ruleset/ALLFACTIONS/weapons_turrets.rul
Ruleset/BALANCE/ballistics_IG.rul
Ruleset/BALANCE/ballistics_ammo.rul
Ruleset/BALANCE/las.rul
Ruleset/BALANCE/las_ammo.rul
Ruleset/ENEMY/GENE/weapons_gene.rul
Ruleset/ENEMY/ORK/weapons_ORK.rul
Ruleset/ENEMY/TZEENTCH/weapons_tzeentch.rul
Ruleset/ENEMY/weapons_chaos.rul
Ruleset/ENEMY/weapons_daemons.rul
Ruleset/IG/weapons_IG.rul
Ruleset/SM/items_SM.rul
Ruleset/scripts/scripts_TU_accuracy_penalty.rul
Ruleset/scripts/scripts_highpower_shot.rul
Ruleset/scripts/scripts_plasma_heat.rul
Ruleset/scripts/scripts_statsforNerds.rul

1. Standardized most sniper rifles in the game to use gaussian damage randomization, improved kneel bonuses, and heavy weapon classifications/recoil where appropriate.
2. Rebalanced some types of sniper ammunition to either be closer to canon representations (Exitus) or existing mechanical conventions with regards to things like typical armor piercing properties and so on (standard sniper rounds).
3. Fire Mode Power Bonus Scripts can now either scale with a % of the user's Firing Accuracy or a flat amount. This bonus can now also be either a flat amount added to weapon power, or a percentage of the weapon's power.

Standardize Sniper Rifle Mechanics; Expand Fire Mode Power Bonus Scripts

---

Language/en-US.yml
Ruleset/40k.rul
Ruleset/ALLFACTIONS/facilities.rul
Ruleset/BALANCE/explosives.rul
Ruleset/ufopedia40k.rul

1. Orbital Beacon costs slightly more money and 200 kill point tokens.
2. Trading Posts now cost 1 million but have 500 storage space, generate 200k per month, and allow the player to purchase Trading Goods for resale at a small profit after a month long delivery time.
3. Krak, frag and photon grenades now weigh slightly less and can actually be thrown an appreciable distance by Guardsmen. Frag grenade and Krak grenade effects standardized. 
Krak grenades now inflict armor ablation.
Frag explosives do much less health and terrain damage, but more wound, energy and morale damage (because they spam shrapnel) and inflict minor armor ablation.

Balance Changes: Orbital Beacon, Trading Post, Grenades

---

Ruleset/40k.rul
Ruleset/ALLFACTIONS/items.rul
Ruleset/ENEMY/armors_chaos.rul
Ruleset/ENEMY/weapons_daemons.rul

1. Juggernauts now have the Khorne rampage mechanics, heightened aggression and Psi Vision to aid them with their hunt. They now have heightened TUs, stamina and stamina recovery to match their distinction as a Khorne steed.
2. Removed redundant orbital strike handsprite.

Remove redundant handsprite; Juggernaut now up to new Khorne standard

---

Ruleset/BALANCE/explosives.rul

Per title; because melee damage typing requires this.

Added Fixed Radius to Frag Explosives

---

Ruleset/IG/manufacture_IG.rul
Ruleset/IG/weapons_IG.rul
Ruleset/scripts/scripts_infection_mechanics.rul

1. Holographic Guardsmen are now immune to zombification.
2. Hologram grenades are too powerful to be purchased; they are now gated with killpoint tokens.

Holographic Guardsman Zombification Bug Fix + Rebalance

---

Language/en-US.yml
Ruleset/40k.rul
Ruleset/ADEPTAS/armors_adeptas.rul
Ruleset/ALLFACTIONS/armors.rul
Ruleset/ENEMY/GENE/armors_gene.rul
Ruleset/ENEMY/KHORNE/armors_khorne.rul
Ruleset/ENEMY/NECRON/units_necron.rul
Ruleset/ENEMY/NURGLE/armors_nurgle.rul
Ruleset/ENEMY/ORK/armors_ORK.rul
Ruleset/ENEMY/TRAITOR_GUARD/armors_traitor_guard.rul
Ruleset/ENEMY/TZEENTCH/armors_tzeentch.rul
Ruleset/ENEMY/armors_chaos.rul
Ruleset/ENEMY/armors_daemon.rul
Ruleset/ENEMY/weapons_chaos.rul
Ruleset/ENEMY/weapons_daemons.rul
Ruleset/IG/armors_IG.rul
Ruleset/SM/armors_SM.rul
Ruleset/eldar.rul
Ruleset/extraSounds.rul
Ruleset/scripts/scripts_intimidation_ability.rul
Ruleset/scripts/scripts_ranged_dodge.rul

1. Added Intimidate scripting/mechanics. Most Khorne units without a ranged attack (Warptalons, Bloodletters, Juggernauts etc) gain the ability to Intimidate that damages TU and Morale in a small AoE and is resisted by Bravery. Certain units (mostly FearImmune) are resistant/immune to Intimidate.
2. Various low level tweaks to Khorne units. 
3. Expanded Stat Gain On Melee Hit/Kill for Khorne weapons.

Khorne Update: Added Intimidation; Expanded Rampage Mechanics

---

Language/en-US.yml
Ruleset/ENEMY/NURGLE/armors_nurgle.rul
Ruleset/ENEMY/SLAANESH/weapons_slaanesh.rul
Ruleset/ENEMY/items_spawner.rul
Ruleset/ENEMY/weapons_chaos.rul
Ruleset/ENEMY/weapons_daemons.rul
Ruleset/scripts/scripts_infection_mechanics.rul

1. Added faction attribution to infection; units that succumb to player caused infection/corruption don't spawn hostile units and refactored the Infection Mechanic code.
2. Expanded Infection damage to scale with ToMana damage.
3. Slightly rebalanced several infection causing weapons; most notably gave the Plague Spewer weapon a snap shot.
4. Added particle trails to Nurgle spit/puke and spewer attacks.

Infection Mechanic Functionality Expansion/Refactor

---

Language/en-US.yml
Ruleset/ADEPTAS/weapons_adeptas.rul
Ruleset/ALLFACTIONS/facilities.rul
Ruleset/ALLFACTIONS/personal_light.rul
Ruleset/ALLFACTIONS/weapons_melta.rul
Ruleset/ALLFACTIONS/weapons_plasma.rul
Ruleset/BALANCE/explosives.rul
Ruleset/BALANCE/las_ammo.rul
Ruleset/BALANCE/plasma_ammo.rul
Ruleset/ENEMY/weapons_chaos.rul
Ruleset/IG/armors_IG.rul
Ruleset/IG/armors_layers_IG.rul
Ruleset/IG/ufopaedia_IG.rul
Ruleset/IG/weapons_IG.rul
Ruleset/SM/items_SM.rul

1. Trading Outpost's trade goods now yield 10% profit rather than 5%.
2. Ammo sale prices across the board reduced; squashed unintended prices that allowed for the highly profitable sale of melta munitions.
3. Ogryns now have a basic default carapace armor that doesn't require manufacture. Manufactured Carapace rebranded as 'Reinforced'; most manufactured Ogryn armor given slightly better protection at the cost of more weight.
4. Ogryns given 33% infection resistance.
5. Lascannons now do gaussian damage rather than 50-200%.
6. Large lascannon charge reduced to 5 shots down from 10.

Minor Balance Tweaks

---

Language/en-US.yml
Ruleset/ARBITES/crafts_arbites.rul
Ruleset/ENEMY/weapons_daemons.rul
Ruleset/IG/armors_IG.rul
Ruleset/IG/crafts_IG.rul
Ruleset/IG/weapons_IG.rul
Ruleset/scripts/scripts_infection_mechanics.rul
Ruleset/scripts/scripts_intimidation_ability.rul

1. Expanded Intimidate mechanics; a character that is totally demoralized will take any overbleed as stun damage then stun overbleed is taken as health damage.
2. Intimidation weapons now have gaussian damage spread.
2. Tzeentch spell tweaks for Flamer and Glimmering One.
3. Chimera speed increased to 150 from 120.
4. Commissars have improved Psi Defence: 50% of Psi Skill (100% for Lord Commissar) + 100% of their current Morale. Commissars also have 33% Intimidation resistance (50% for Lord Commissars).
5. Commented out debug notes for infection mechanics.
6. Improved Heavy Weapon Toolkit description.

Various Tweaks

---

Ruleset/ENEMY/weapons_daemons.rul
Ruleset/IG/manufacture_IG.rul
Ruleset/IG/weapons_IG.rul
Ruleset/SM/manufacture_SM.rul

1. Fixed bug with Heavy Plasma Clip recipe so it makes Heavy Plasma Clips instead of Melta Clips.
2. Added recipes for Light Bolter Short ammo, Lasgun Clips, Lasgun Hotshot, and Ripper Guns and Ripper Gun Clips.
3. Ripper Guns now have minor armor penetration and slightly better  armor ablation.

Ammo Fixes/Tweaks

---

Ruleset/IG/armors_IG.rul
Ruleset/scripts/scripts_infection_mechanics.rul
Ruleset/scripts/scripts_intimidation_ability.rul

1. Devotion now affords protection from Chaos corruption/infection at a rate of 1% resistance per 2 points of Devotion above 50.
2. Halved the stun and health damage the intimidate ability can inflict.
3. Added rapid morale recovery for manned turret armors.

Script Tweaks

---

Language/en-US.yml
Ruleset/ALLFACTIONS/armors.rul
Ruleset/ALLFACTIONS/items.rul
Ruleset/ALLFACTIONS/ufopaedia_assistance.rul
Ruleset/ALLFACTIONS/units_turrets.rul
Ruleset/ARBITES/armors_arbites.rul
Ruleset/IG/armors_IG.rul

1. Added information about Corruption/Infection mechanics to the Codex/Ufopedia under Rosigma help.
2. Manned turrets lose fear immunity in exchange for rapid Morale recovery.
3. Servitor kit tweaked; the repair functionality has been rolled into its medicae kit, and they have a crane based melee attack. Servitors now have 50% Infection and Intimidation resistance.

Corruption/Infection Ufopedia Addition

---

Ruleset/ADEPTAS/armors_adeptas.rul
Ruleset/ENEMY/GENE/armors_gene.rul
Ruleset/ENEMY/ORK/armors_ORK.rul
Ruleset/ENEMY/TRAITOR_GUARD/armors_traitor_guard.rul
Ruleset/ENEMY/TZEENTCH/armors_tzeentch.rul
Ruleset/ENEMY/armors_chaos.rul
Ruleset/IG/armors_IG.rul
Ruleset/SM/armors_SM.rul
Ruleset/eldar.rul
Ruleset/scripts/scripts_intimidation_ability.rul

1. Intimidation respects fear immunity; going forward we'll probably have to review what should and should not be fear immune (manned stuff like Sentinels should not be fear immune for example). I've adjusted a bunch of stat blocks on this basis thus far.
2. Intimidation after Bravery reductions is only 25% effective versus 2x2 due to hitting 4x.

Intimidation Tweaks 2

---

Language/en-US.yml
Ruleset/ALLFACTIONS/items.rul
Ruleset/IG/armors_IG.rul
Ruleset/IG/ufopaedia_IG.rul

1. Fixes white spaces.
2. Normalizes some UFOPAEDIA titled entries to UFOPEDIA.
3. Fixes side armor for Ogryn Bulgryn Slab armor to be at an appropriate value (110 up from 70).
4. Fixes Reinforced Ogryn Carapace armor description.
5. Fixes explosion falloff for Orbital Strike (fix of opportunity).

Ogryn Armor Tweaks

---

Ruleset/scripts/scripts_infection_mechanics.rul

1. Friendly infected/corrupted units the player kills with friendly fire will grant the Emperor's Mercy; they will not turn into daemons on death.

Player Killing Friendly Units Gives Them The Emperor's Mercy

---

Ruleset/ENEMY/weapons_daemons.rul
Ruleset/scripts/scripts_bomberman.rul

1. Suicide spawner bombs no longer spawn friendly units.

Bomberman Deathbomb Fix 2.0

---

Ruleset/40k.rul
Ruleset/ENEMY/items_spawner.rul

1. Surface base generators are now immune to infection and intimidation.
2. Nurgle unit spawner grenades now have proper reductions to their health damage.

Fixes Plasma Generators to be Infection Proof; Tweaks to Nurgle Spawners

---

Ruleset/ADEPTAS/items_adeptas.rul
Ruleset/IG/weapons_IG.rul

1. Officer's Sword now has a significant Stun cost and has a slight increase to its morale cost. Minor devotion scaling added.
2. Lead by Example nerfed; no longer provides healing and has a stun cost.
3. Whitespace removal.

Nerf TU Multipliers

---

Ruleset/scripts/scripts_damage_feedback.rul

1. Added Hit FX Scripts:
- When HP damage is dealt, target is flash highlighted in red. 
- When only Armor damage is dealt, target is flash highlighted in white.

Added Hit FX Scripts

---

Ruleset/ADEPTAS/armors_adeptas.rul
Ruleset/BALANCE/melta.rul

1. Slightly improved armor of Meltalance Sentinel.
2. Significantly improved range of Meltalance Sentinel to 15 Snap, 20 Aimed; meant to be a longer range, vehicle mounted Conversion Beamer Melta.
3. Slightly decreased TU cost of Snap from 33% to 30% and Aimed from 60% to 55%.
4. Meltalance has Gaussian damage variance; increased base damage 150 to 180.

Adeptas Meltalance Sentinel Improved

---

Ruleset/ADEPTAS/weapons_adeptas.rul
Ruleset/BALANCE/ballistics_ammo.rul
Ruleset/IG/manufacture_IG.rul
Ruleset/SM/manufacture_SM.rul

1. Added missing ammo compatibility with Kraken Penetrators and Metal Storm for Adeptas weapons.
2. Added some missing ammo crafting recipes.
3. Added missing category tags for Adeptas weapons.
4. Added missing 40mm grenade and Adeptas hand/light flamethrower recipes.
5. Made the cost/store buy and sell of 40mm grenades more sane.

Adeptas Ammo Compatibility

---

Ruleset/ADEPTAS/crafts_adeptas.rul
Ruleset/ARBITES/crafts_arbites.rul
Ruleset/IG/crafts_IG.rul
Ruleset/SM/GREY KNIGHTS/crafts_GK.rul

1. Rosigma Thunderbolt improvements made standard.
2. Adeptas Avenger stats made more in line with the Rosigma Lightning; given an additional +7 hit bonus due to devoted gunner.
3. Xiphon given 1 armor, 5 dodge, 5 hit bonus and repair rates on par with other basic interceptors; less speedy and maneuverable but more accurate.

Unsuckifying Thunderbolts/Adeptas Avenger/Xiphon

---

Ruleset/BALANCE/las.rul
Ruleset/SM/items_SM.rul
Ruleset/scripts/scripts_abilities_miracles.rul

1. Most Lascannons now take 30 TUs to reload; they are cumbersome heavy weapons.
2. Vostroya Autofire reduced to 2 shots, but made more accurate.
3. Adeptas Spirit of the Martyr miracle now removes all corruption/infection damage.
4. Droppod Stormturret Spawners now non-recoverable.

Minor Changes

---

Language/en-US.yml
Ruleset/ADEPTAS/weapons_adeptas.rul
Ruleset/BALANCE/las.rul
Ruleset/ENEMY/ORK/weapons_ORK.rul
Ruleset/ENEMY/TZEENTCH/weapons_tzeentch.rul
Ruleset/ENEMY/weapons_chaos.rul
Ruleset/ENEMY/weapons_daemons.rul
Ruleset/IG/weapons_IG.rul
Ruleset/SM/items_SM.rul
Ruleset/alienDeployments_40k.rul
Ruleset/scripts/scripts_highpower_shot.rul
Ruleset/scripts/scripts_plasma_heat.rul
Ruleset/scripts/scripts_statsforNerds.rul

1. Expanded functionality of fire mode power bonus scripts.
2. Minor rebalance of Inquisition Longlas and Exitus Rifle.
3. Mission failure penalties for base raids no longer capped at -200; now they are equal to half the bonus for success.

Expanded Fire Mode Power Bonus Scripts/Abort Rebalance

---

Ruleset/IG/weapons_IG.rul

1. IG's Heavy Sniper Rifle now can snap shot (badly).
2. Improved Firing Accuracy aimed shot damage bonus for the IG Heavy Sniper Rifle (50% of FA up from 25%).

Guard Heavy Sniper Rifle Fix

---

Ruleset/ADEPTAS/armors_adeptas.rul
Ruleset/ADEPTAS/items_adeptas.rul
Ruleset/ADEPTAS/weapons_adeptas.rul
Ruleset/ENEMY/weapons_daemons.rul
Ruleset/IG/weapons_IG.rul
Ruleset/SM/items_SM.rul

1. Inspire type abilities no longer damage terrain/objects.
2. Juggernaut melee has a Range 1 lunge so it can now attack you up elevators and react attack more readily.
3. Adeptas assassin armors have slightly improved under armor to prevent taking damage from droppods and to equalize it with rear armor.
4. Lead By Example Stun slightly increased to compensate for the massive stamina regeneration it affords.

Minor Bug Fixes/Balance Changes

---

Language/en-US.yml
Ruleset/40k.rul
Ruleset/BALANCE/explosives.rul
Ruleset/ENEMY/TRAITOR_GUARD/armors_traitor_guard.rul
Ruleset/ENEMY/weapons_chaos.rul
Ruleset/IG/weapons_IG.rul
Ruleset/SM/items_SM.rul
Ruleset/extraSprites_HANDOB.rul
Ruleset/scripts/scripts_damage_feedback.rul

1. Added more language lines to grenade priming/unpriming for clarity/QoL.
2. Beacons and Melta Bombs now weight 30 pounds; these are not meant to be combat grenades.
3. Moved the Inq Multilaser to the Inquisition Stormtrooper weapon section; slightly improved its autofire, gave it a 33% TU 3 shot burst snap, and greatly increased its kneel bonus. This weapon benefits most from setting up a static emplacement with it.
4. Fixed hand sprite issues with the Inquisitorial Flamer.
5. Standardized the Servo Skull to be compliant with baseline grenade stats.
6. Named the damage indicator scripts.
7. Added missing overcharge damage bonus to Inquisition Plasma Rifle
8. Gave Chaos Sentinels a dumbfire rocket pod that fires superfrag missiles; hopefully this will fix its passivity issues.

Bug Fixes and Minor Improvements for 2.2A

---

Ruleset/40k.rul
Ruleset/ENEMY/GENE/weapons_gene.rul
Ruleset/ENEMY/TRAITOR_GUARD/armors_traitor_guard.rul
Ruleset/ENEMY/weapons_chaos.rul
Ruleset/IG/weapons_IG.rul

1. Fixes Chaos Sentinels not using their main guns (it prioritized the short range stomp over all other weapons).
2. Adds the Superfrag, Krak and Guided HE launchers for the Chaos Sentinel.
3. HE heavy explosives have minor pre-armor ablation now.
4. Improved GSC Needler penetration slightly.
5. Gave Sentinel the Sniper 50 AI property so it can take advantage of friendly spotters.

Fixes Chaos Sentinel; Tweaks Weapons

---

Ruleset/BALANCE/explosives.rul
Ruleset/IG/armors_IG.rul
Ruleset/IG/weapons_IG.rul
Ruleset/scripts/scripts_heavy_weapon_teams.rul
Ruleset/scripts/scripts_ranged_dodge.rul

1. Added infrastructure for Flat and Percentile dodge reduction tags.
2. Exitus Rifle has 100% dodge reduction; no one can dodge a Vindicare.
3. Vindicare Assassin now has 50% dodge with 4 dodges; he's a proper temple assassin with Invul 4+.
4. Removed copy pasta from Eldar Grenade.
5. Slightly reduced the aimed shot cost of the Heavy Mortar from 55% of TUs to 50%.

Added Anti-Dodge Tags; Minor Balance Tweaks/Fixes

---

Ruleset/BALANCE/ballistics_ammo.rul
Ruleset/IG/manufacture_IG.rul
Ruleset/IG/soldiers_IG.rul

1. Vindicare ammo is now made in bundles of 5, is more expensive and requires 20 Honor Tokens per batch.  Requires 200 man hours per batch up from 100.
2. Vindicare starting min/max, cap, training stats all increased substantially (this is a Temple Assassin).
3. Vindicare monthly salary/upkeep cost increased to 500k
4. Vindicare recruitment cost increased to 2 mil, and 1000 Honor.

Vindicare Rebalance

---

Ruleset/BALANCE/explosives.rul
Ruleset/SM/items_SM.rul

1. Inq Multimeltas no longer recoverable/removable.
2. Photon grenades use the new grenade standard.

Hot Fix for Inq Multimelta

---

Ruleset/SM/GREY KNIGHTS/soldierTransformations_GK.rul
Ruleset/SM/soldierTransformations.rul

1. Dreadnought construction fixed for DW.
2. Dreadnoughts now cost 300 Honor points and require 10 Ceramite.

Fixes DW Dreadnoughts Not Being Buildable

---

Ruleset/ALLFACTIONS/weapons_turrets.rul
Ruleset/ARBITES/armors_arbites.rul
Ruleset/ENEMY/NURGLE/armors_nurgle.rul
Ruleset/ENEMY/armors_daemon.rul
Ruleset/ENEMY/corpses_chaos.rul
Ruleset/ENEMY/weapons_daemons.rul
Ruleset/IG/units_IG.rul
Ruleset/IG/weapons_IG.rul
Ruleset/commendations.rul

1. Added Battle Tested commendations entry.
2. Nerfed battle cannon reaction fire (reduced accuracy and snap range)
3. Standardized Daemon senses to be minimum 40 darkness visibility, 33 heat vision and 5 psi vision.
4. Increased standardization of krak explosives RE: Item and Tile damage.

Turret and Daemon Sense Tweaks

---

Ruleset/40k.rul
Ruleset/IG/manufacture_IG.rul
Ruleset/IG/soldierTransformation_IG.rul
Ruleset/OTHER/manufacture_killpoints.rul
Ruleset/research_ROSIGMA.rul

1. Battle Tested commendation is now needed for all officer transforms along with 50 Bravery.
2. Token cost for Orbital Strikes increased from 200 to 400. Monetary cost increased to 1 million.
3. Psyker Token Cost increased from 120 to 500.
4. Veteran promotion Token Cost increased from 60 to 100.
5. No more free Honor Tokens just for researching Psyker Requiisiton.

Battle Tested Fixes; Token Cost Tweaks

---

Ruleset/ALLFACTIONS/weapons_turrets.rul
Ruleset/IG/soldierTransformation_IG.rul

1. Leman Russ Turret can snap shot once, but with short range, requiring 10 Energy.
2. Initial Battle Tested rank recognized.

Fixing Leman Russ Turret and Battle Tested

---

Ruleset/IG/soldiers_command_IG.rul
Ruleset/soldierBonuses.rul

1. Boneheads now heal at the same rate Ogryns do.
2. Bonehead upgrade now costs what it should since we're no longer in testing.

Boneheads Get Their Healing Factor and Proper Costing!

---

Ruleset/IG/manufacture_IG.rul
Ruleset/IG/weapons_IG.rul
Ruleset/soldierBonuses.rul

1. Boneheads, Ripper Gun Flechette Drums Purchase/Manufacture now requires STR_MIDTIER_PREREQ instead of STR_MIDTIER_GUARDSMEN so all paths with Ogryn Requisition can benefit from these.
2. Price of Ripper Gun Flechettes slightly increased to make manufacturing it a bit more competitive.
3. Ripper Gun Flechette TU/Stun/Energy damage slightly increased.
4. Ripper Gun Incendiary TU/Energy damage increased and slightly increased. Stun damage slightly decreased.
5. Ripper Gun one-handed penalty increased to 50% up from 25%.

Ogryn/Bonehead Prereq Fixes

---

Ruleset/ALLFACTIONS/personal_light.rul
Ruleset/IG/armors_IG.rul
Ruleset/IG/soldiers_IG.rul
Ruleset/IG/soldiers_command_IG.rul

1. Squats buffed:
* Stun recovery scales with current Energy and current Health.
* Energy recovery  scales with current Health.
* Squats now have mid level resistance to GSC infection.
* Squats now have halved wound recovery time.
* Squat Health and Stamina training maximums improved.
* Squats now yield +1 command point.
2. Kriegers now get higher initial Bravery and all Krieg armor types get Krieger Mind Control resistance as they should.
3. Beastman infection/corruption resistance reduced from 50% to 33%, but now have 33% faster wound recovery time.
4. Added TU, Stamina and Reaction penalties to Medic variants of armor.

Soldier/Armor Tweaks

---

Ruleset/IG/weapons_IG.rul

1. Per title. Incredibly overdue. Decreased armor penetration from 75% to 60%, changed damage scaling from PsiStrength to Psi * 0.001. Increase cast cost by +5 Stun and +5 Morale.

Thunderclap Nerf

---

Ruleset/scripts/scripts_bomberman.rul
Ruleset/soldierBonuses.rul

1. Per title.
2. Also Ogryn Bonehead surgery now requires the Veteran commendation instead of merely Battle Tested.

Bomberman Kamikazi Activates Only On Melee Attack Now

---

Language/en-US.yml
Ruleset/BALANCE/las_ammo.rul
Ruleset/scripts/scripts_hotshot_penalty.rul
Ruleset/ufopedia40k.rul

1. Per title. Each shot made with a Hotshot las packs imposes a small cumulative accuracy penalty until the start of the player's next turn as the pack and weapon get hot. This penalty can be reset by reloading the weapon.

Hotshot Las Munitions Have Degrading Accuracy
