Ruleset/ufopedia40k.rul
until the research required to buy is done.
=> Hide Handflamer codex page.

Ruleset/research40k.rul
Added STR_THREAT_ONE interrogation reward  to more enemies to a lot of mid-high level enemies to prevent armor upgrade lock in mid-late runs.
=> Added STR_THREAT_ONE interrogation reward to more enemies

Ruleset/scripts/scripts_limited_flight.rul
player units flying move 50% faster
=> faster flight

Language/en-US.yml, Ruleset/ALLFACTIONS/ufopaedia_assistance.rul
Still needs codex code and revision
=> New article for assistance section of codex

Language/en-US.yml, Ruleset/SM/GREY KNIGHTS/Research_GK.rul, Ruleset/SM/GREY KNIGHTS/manufacture_GK.rul
Mostly minor changes.
White spaces removed.
Fixed some GK Ufopaedia armor descriptions.
The Grey Knight Force Halberd is now researchable early for Grey Knights as the Mastercrafting prerequisite has been removed, but it now costs 50 Imperial Tokens (also it's expensive for the early game), something else to consider when managing the token economy critical to this subfaction.
=> Grey Knight Update Part 2

Language/en-US.yml, Language/ru.yml, Ruleset/ALLFACTIONS/personal_light.rul, Ruleset/SM/GREY KNIGHTS/armors_GK.rul, Ruleset/SM/GREY KNIGHTS/armors_layers_GK.rul, Ruleset/SM/GREY KNIGHTS/armors_scripts_GK.rul, Ruleset/SM/GREY KNIGHTS/ufopaedia_GK.rul, Ruleset/SM/items_SM.rul, Ruleset/SM/scripts_SM.rul, Ruleset/ufopedia40k.rul, Ruleset/vars40k.rul
The GK Holocaust spell now functions as a deadly psychic flamethrower; beware its splash damage!
All GK armors now scale up to Captain level.
Crozius has been rebalanced to sanity.
Various error fixes and improvements.
=> Various Fixes and Improvements

Ruleset/SM/items_SM.rul
Melee now has proper scaling for the Force Halberd.
=> Force Halberd Bug Fix

Ruleset/40k.rul, Ruleset/ENEMY/NURGLE/armors_nurgle.rul, Ruleset/ENEMY/NURGLE/units_nurgle.rul, Ruleset/ENEMY/armors_daemon.rul, Ruleset/ENEMY/weapons_daemons.rul, Ruleset/SM/GREY KNIGHTS/armors_GK.rul, Ruleset/SM/scripts_SM.rul
1. Eliminated a bunch of white space.
2. Minor GK bug fixes; Captain GK Techmarines now get Thunderfire spawners.
3. Added Yankes stat leech scripts; expanded functionality with stat gain on kill.
4. Various daemons had stats tweaked to match their canon properties. Most Nurgle units now have regeneration of some kind based on their current hit points. Bloodletters regain most stats on kill and damage.
=> Daemon Updates Part 1

Ruleset/40k.rul, Ruleset/ADEPTAS/manufacture_adeptas.rul.rul, Ruleset/ALLFACTIONS/manufacture.rul, Ruleset/ALLFACTIONS/weapons_melta.rul, Ruleset/BALANCE/ballistics_ammo.rul, Ruleset/ENEMY/ORK/weapons_ORK.rul, Ruleset/ENEMY/weapons_daemons.rul, Ruleset/IG/manufacture_IG.rul, Ruleset/SM/manufacture_SM.rul
1. Players can now produce more ammunition types (Bolter Kraken rounds, metal storm etc) at the cost of resources.
2. More ammunition is now manufactured in batches for QoL; resource and monetary costs have been adjusted accordingly.
3. Nerfs to Khorne weapon TU recovery on kill/damage.
4. Necron weapons now have properties that are more canonically accurate; Gauss weapons now strip armor rather than ignore it. Synaptic Disruptor now deals stun typed damage and thus is only effective vs organics, while inflicting stat debuffs. Gauss Flayers and Gauss Blasters now have axe bayonets.
=> Ammo (Mostly) Update + Necron Weapon Revisions

Ruleset/SM/armors_SM.rul, Ruleset/scripts/scripts_limited_flight.rul
Added melee punch to some chaos armors.
Created a jump pack variant with melee punch.
Replaced the regular jump pack on power armors with the punching one.
Tested - seems to work fine.
=> Melee on jump packs and chaos armor

Language/en-US.yml, Ruleset/ADEPTAS/armors_adeptas.rul, Ruleset/ENEMY/GENE/weapons_gene.rul, Ruleset/ENEMY/NURGLE/armors_nurgle.rul, Ruleset/ENEMY/NURGLE/units_nurgle.rul, Ruleset/ENEMY/SLAANESH/weapons_slaanesh.rul, Ruleset/ENEMY/weapons_chaos.rul, Ruleset/ENEMY/weapons_daemons.rul, Ruleset/IG/armors_IG.rul, Ruleset/SM/GREY KNIGHTS/armors_GK.rul, Ruleset/SM/armors_SM.rul, Ruleset/scripts/scripts_bomberman.rul, Ruleset/scripts/scripts_carry_TU_damage_till_next_turn.rul, Ruleset/scripts/scripts_infection_mechanics.rul
-Added functionality to the infection infrastructure, including respecting munition types.
-Rebalanced infection parameters, and weapons and armor that use/interact with infection after testing.
-Added on-death functionality to Bomberman scripts; these special on-death grenades do not work properly with FixedWeapon.
=> Improved Infection Infrastructure

Language/en-US.yml, Ruleset/ENEMY/GENE/armors_gene.rul, Ruleset/ENEMY/NURGLE/armors_nurgle.rul, Ruleset/ENEMY/NURGLE/units_nurgle.rul, Ruleset/ENEMY/TZEENTCH/armors_tzeentch.rul, Ruleset/ENEMY/weapons_chaos.rul, Ruleset/ENEMY/weapons_daemons.rul, Ruleset/scripts/scripts_infection_mechanics.rul
-Units can now have different infection resistance types to Nurgle, GSC or Slaanesh infection/corruption or some combination thereof.
-Corrected certain Tzeentch units having Nurgling claws for some reason.
-Added GSC infection immunity to GSC units.
=> Adds Typed Infection Resistance

Ruleset/ALLFACTIONS/armors.rul, Ruleset/ALLFACTIONS/units_turrets.rul
Also removed "STR_ELDAR_TURRET_P" attributes because they 1:1 duplicate the 40k ones, with no visible changes.
Not sure if that was me who accidently copied it or if it was like that in the ROSIGMA.
Fixed Tarantula's ability to move.
=> Turrets consistency 2.1

Ruleset/SM/items_SM.rul, Ruleset/SM/manufacture_SM.rul
-Tomes now both require the Library facility researched and built at a base to manufacture.
-Tomes cost substantially more to manufacture and cost honor tokens. Tomes of Speed cost the most (1000).
=> Tomes Now Much Harder to Get

Language/en-US.yml, Ruleset/ENEMY/NURGLE/armors_nurgle.rul, Ruleset/SM/scripts_SM.rul
-Fixes Nurgle Plaguespewer armor yielding the wrong corpse.
-Gives the Nurgle Putrifier Corpse a proper name.
-Fixes GK Holocaust spell costs.
=> Minor Tweaks

Ruleset/IG/armors_IG.rul, Ruleset/scripts/scripts_infection_mechanics.rul
Per title. Adds infection immunity to vehicle armors lacking it.
=> Fixes Certain Vehicles Being Vulnerable to Infection

Ruleset/SM/manufacture_SM.rul
=> Fixes Tome Requisites for SoB

Ruleset/SM/GREY KNIGHTS/manufacture_GK.rul
=> Added Killpoint Token to Grey Knight Requisition Recipe

Ruleset/ALLFACTIONS/weapons_plasma.rul
=> Fixes Sprite Issues With Dekker Plasma Rifle

Ruleset/scripts/scripts_statsforNerds.rul
=> Minor Fix to Custom Scripted Parameters in Stats for Nerds

Language/en-US.yml, Ruleset/ALLFACTIONS/armors.rul, Ruleset/ALLFACTIONS/items.rul
Embracing the HWP manufacture kludge.
=> Orbital Beacon Fix

Ruleset/40k.rul, Ruleset/ENEMY/KHORNE/armors_khorne.rul, Ruleset/ENEMY/armors_daemon.rul, Ruleset/ENEMY/weapons_chaos.rul, Ruleset/ENEMY/weapons_daemons.rul, Ruleset/SM/items_SM.rul, Ruleset/scripts/scripts_intimidation_ability.rul
1. Expanded new standards to Flying Daemons, Khorne Valkyria and Khorne Assassins
2. Expanded Intimidate functionality.
=> Khorne Update Part 2

Ruleset/BALANCE/las.rul, Ruleset/IG/weapons_IG.rul
1. Normalized the heavy frag missile to the new standard frag munition conventions.
2. Added Gaussian random type to many low fire rate lascannon style weapons.
=> Minor Weapon Tweaks

Ruleset/scripts/scripts_intimidation_ability.rul
=> Intimidation Reactions Now Ignore Intimidation Immune Targets

Ruleset/ALLFACTIONS/armors.rul, Ruleset/scripts/scripts_infection_mechanics.rul
1. Added additional debug commentary, and flat reduction mechanics.
2. Servitors made Pain and Infection immune because they cannot be targeted with medkits due to hardcoded limits.
=> Infection System Minor Tweaks

Ruleset/IG/weapons_IG.rul
=> Frag Mortar Ammo Added

Ruleset/IG/weapons_IG.rul, Ruleset/SM/items_SM.rul
1. Tweaked Ammo Mortar Colors.
2. Standardized photon drum grenades.
=> Minor Ammo Tweaks

Ruleset/ENEMY/weapons_daemons.rul, Ruleset/scripts/scripts_bomberman.rul
=> Fixes Picking Up Bomberman Script Suicide Bombs

Ruleset/ENEMY/ORK/weapons_ORK.rul, Ruleset/ENEMY/weapons_chaos.rul, Ruleset/extraSprites.rul
=> Fixes Minor Animation/Sprite Issues With Some Weapons

Ruleset/ENEMY/ORK/weapons_ORK.rul
=> Necron Weapons Getting Missing Autofire; Improved Tabletop Accuracy

Ruleset/research_ROSIGMA.rul, Ruleset/scripts/scripts_statsforNerds.rul
1. Per title.
2. Grey Knights gives Force Halberd research for free.
=> Added Corruption/Infection and Intimidation Metrics to Stats for Nerds

Language/en-US.yml, Ruleset/SM/GREY KNIGHTS/armors_GK.rul, Ruleset/SM/items_SM.rul
1. GK Chaplains get Inspire and 40 Devotion at Captain rank.
2. Fixed spawned Thunderfires having recoverable shells.
3. Fixed Tome of Speed.
=> Minor GK Tweaks

Ruleset/ENEMY/NECRON/units_necron.rul, Ruleset/ENEMY/ORK/weapons_ORK.rul, Ruleset/SM/items_SM.rul, Ruleset/scripts/scripts_tenacious_enemies.rul
1. Scarabs now self-destruct when destroyed in a powerful fragmentation explosion.
2. Lychguard Dispersion Shield now has snap shot mode for improved reaction fire.
=> Necron Tweaks

Ruleset/SM/scripts_SM.rul, Ruleset/scripts/scripts_soldier_healing.rul
=> Fixes Expedited Healing for Space Marines so it Works

Ruleset/ADEPTAS/crafts_adeptas.rul
1. Added stormbolter turrets to the SoB droppods.
=> Stormbolters for SoB Droppods

Ruleset/extraSprites.rul
=> Missing Sprite Index Re-Added

Ruleset/ADEPTAS/weapons_adeptas.rul
=> Added De'az Bolter Ammo Compatibility

Ruleset/scripts/scripts_infection_mechanics.rul
1. Minor simplification for infection scripts.
2. Removes a typo negative sign from Devotion based infection resistance.
=> Minor Improvement to Infection Script

Ruleset/SM/manufacture_SM.rul
=> Fixes Stormbolter Manufacturing Bug

Ruleset/SM/items_SM.rul, Ruleset/extraSprites_HANDOB.rul
1. Per title.
2. Added helpful documentation to the handob file.
=> Fixes Some Remaining Handob Issues

Ruleset/ENEMY/NURGLE/armors_nurgle.rul, Ruleset/ENEMY/armors_daemon.rul
=> Hotfix for Bomberman Tag

Language/en-US.yml, Ruleset/IG/weapons_IG.rul, Ruleset/scripts/scripts_bonehead_orders.rul
=> Added Rebate for Using Bonehead Ordurrs With None Selected

Ruleset/extraSprites.rul
Did I just not upload the extra sprites before? No idea how this happened
=> Fixed missing sprites

Ruleset/research_ROSIGMA.rul
=> Bonehead Research Surgery Now Requires All Dependencies

Ruleset/IG/manufacture_IG.rul
=> Fixes the Ripper Pistol Requisition Name

Ruleset/ENEMY/NURGLE/armors_nurgle.rul, Ruleset/scripts/scripts_bomberman.rul
=> Update to Make Sure Dummy Unit Isn't Overkilled

Ruleset/scripts/scripts_infiltrator.rul
=> Typo Quickfix RE: Infiltrator Scripts

Ruleset/advancedTurrets.rul
=> Remove Leman Russ Specific Unit Select Sounds

Ruleset/ENEMY/ORK/weapons_ORK.rul, Ruleset/research_ROSIGMA.rul
=> Necron Weapons Now Require Necrontech Research

Ruleset/advancedTurrets.rul
=> Fix Chimera Pathing Plus Turret Select Sounds Typopasta
